### ISSUE TITLE
board.json and conf.json wiped after updating to 1.6.6.b

### ISSUE THREAD

**Issue by fvalen** [MassiveCraft/Factions#99]
When updating to factions 1.6.6.b I got this error.

2012-03-03 22:23:08 [SEVERE] Error occurred while enabling Factions v1.6.6b (Is it up to date?): org.bukkit.plugin.PluginDescriptionFile.getCommands()Ljava/util/Map;
java.lang.NoSuchMethodError: org.bukkit.plugin.PluginDescriptionFile.getCommands()Ljava/util/Map;
    at com.massivecraft.factions.zcore.MPluginSecretServerListener.<init>(MPluginSecretServerListener.java:24)
    at com.massivecraft.factions.zcore.MPlugin.preEnable(MPlugin.java:76)
    at com.massivecraft.factions.P.onEnable(P.java:75)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:230)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:1057)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:380)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:199)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:182)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:357)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:344)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:175)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:408)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)

board.json and conf.json were completely wiped. All factions land claims are gone.... forever.
